---@meta _
error('Cannot require meta file')

---Options for `docker container ls`
---@class docker.cli.container.ls.Opts
---
---Show all containers (default shows just running)
---@field all?    boolean
---
---Filter output based on conditions provided
---@field filter? table<string, string>
---
---Show n last created containers (includes all states)
---@field last?   integer
---
---Show the latest created container (includes all states)
---@field latest? boolean
---
---Display total file sizes
---@field size?   boolean
---
---Format output using a custom template:
---'table':            Print output in table format with column headers (default)
---'table TEMPLATE':   Print output in table format using the given Go template
---'json':             Print in JSON format
---'TEMPLATE':         Print output using the given Go template. Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates
---@field format?   string
