---@meta _
error('Cannot require meta file')

---Options for `docker image ls`
---@class docker.cli.image.ls.Opts
---
---Show all images (default hides intermediate images)
---@field all?     boolean
---
---Show digests
---@field digests? boolean
---
---Filter output based on conditions provided
---@field filter?  table<string, string>
---
---Format output using a custom template:
---'table':            Print output in table format with column headers (default)
---'table TEMPLATE':   Print output in table format using the given Go template
---'json':             Print in JSON format
---'TEMPLATE':         Print output using the given Go template. Refer to https://docs.docker.com/go/formatting/ for more information about formatting output with templates
---@field format?   string
