---
name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim_version: ["nightly"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Tests
        uses: nvim-neorocks/nvim-busted-action@v1
        with:
          nvim_version: ${{ matrix.nvim_version }}

